[package]
name = "command_isprime"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
emoji.workspace = true
gmp-mpfr-sys = { version = "1.7.1", features = ["use-system-libs"] }
poise.workspace = true
poise_error.workspace = true
rug = "1.30.0"
shared.workspace = true
tokio.workspace = true
