[package]
name = "database"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
postcard.workspace = true
poise_error.workspace = true
serde.workspace = true
shared.workspace = true
sled.workspace = true
