[package]
name = "activity"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
poise.workspace = true
postcard.workspace = true
rand.workspace = true
tokio.workspace = true
tracing.workspace = true
