[package]
name = "shared"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
poise.workspace = true
poise_error.workspace = true
postcard.workspace = true
serde.workspace = true
sled.workspace = true
topgg.workspace = true
